#!/bin/sh
# gen_homebrew_formula.sh — emit a Homebrew formula for a published seqfw release.
#
# The formula pins each platform's release tarball by sha256, so it can only be
# generated *after* `release.yml` has built and uploaded the binaries for a tag.
# Run it, then drop the output into your tap repo at Formula/seqfw.rb.
#
#   ./scripts/gen_homebrew_formula.sh v0.1.0 > Formula/seqfw.rb
#
# Requires: curl, and sha256sum or shasum.
set -eu

REPO="catancs/seqfw"
VERSION="${1:?usage: gen_homebrew_formula.sh vX.Y.Z}"
VER_NOV="${VERSION#v}"

sha_for() {
  _url="https://github.com/$REPO/releases/download/$VERSION/$1"
  _tmp="$(mktemp)"
  curl -fsSL "$_url" -o "$_tmp" || { echo "gen: download failed: $_url" >&2; exit 1; }
  if command -v sha256sum >/dev/null 2>&1; then
    sha256sum "$_tmp" | awk '{print $1}'
  else
    shasum -a 256 "$_tmp" | awk '{print $1}'
  fi
  rm -f "$_tmp"
}

echo "gen: fetching release assets for $VERSION …" >&2
SHA_MAC_ARM="$(sha_for "seqfw-aarch64-apple-darwin.tar.gz")"
SHA_MAC_X86="$(sha_for "seqfw-x86_64-apple-darwin.tar.gz")"
SHA_LINUX_X86="$(sha_for "seqfw-x86_64-unknown-linux-musl.tar.gz")"

base="https://github.com/$REPO/releases/download/$VERSION"

cat <<EOF
# typed: false
# frozen_string_literal: true

# Homebrew formula for seqfw — generated by scripts/gen_homebrew_formula.sh.
class Seqfw < Formula
  desc "Firewall for genomic data: validate FASTQ/FASTA/VCF at the trust boundary"
  homepage "https://github.com/$REPO"
  version "$VER_NOV"
  license "Apache-2.0"

  on_macos do
    on_arm do
      url "$base/seqfw-aarch64-apple-darwin.tar.gz"
      sha256 "$SHA_MAC_ARM"
    end
    on_intel do
      url "$base/seqfw-x86_64-apple-darwin.tar.gz"
      sha256 "$SHA_MAC_X86"
    end
  end

  on_linux do
    on_intel do
      url "$base/seqfw-x86_64-unknown-linux-musl.tar.gz"
      sha256 "$SHA_LINUX_X86"
    end
  end

  def install
    bin.install "seqfw"
  end

  test do
    assert_match "seqfw", shell_output("#{bin}/seqfw --version")
  end
end
EOF
